### ISSUE TITLE
Chatbot is not responding 

### ISSUE THREAD

**Issue by mhuntoa** [flipay/chopperbot#13]
![D93763B9-7A0D-40EF-B520-85BCA889FC6E](https://user-images.githubusercontent.com/26888129/74944247-546bd700-5428-11ea-9b9e-29cd8e966da3.jpeg)

**Comment by turboza** [comment]
Thanks a lot for reporting. It is back online already.

It seems that if the bot has not been used for a moment, the instance will be terminated since it is hosted in the free service. Looking for the workaround.
